import { Place } from 'types';

const _url = process.env.NEXT_PUBLIC_BASE_IMAGE_API;

const places: Place[] = [
  {
    id: '81',
    name: 'Bekasi',
    cityName: 'KOTA BEKASI',
    buildings: [
      {
        id: '180',
        name: 'Rukita PHB Harapan Indah Bekasi',
        address: 'Ruko Permata Harapan Baru Blok H 51-52, Jalan Pejuang, Medan Satria, Bekasi, Jawa Barat',
        city: { id: '3275', name: 'KOTA BEKASI' },
        district: { id: '3275061', name: 'MEDAN SATRIA' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3275061003', name: 'MEDAN SATRIA' },
        lat: -6.182765,
        lon: 106.989155,
        startFrom: 1800000,
        discount: null,
        published: true,
        slug: 'phb-harapan-indah-bekasi',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-PHB-Harapan-Indah-Bekasi_Mei2020_95_edited/caa0f7d418dac757b6aef0b5792737d2.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=OHBnqv5kIwI',
        rukitaOption: false
      }
    ]
  },
  {
    id: '17',
    name: 'Bintaro',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '158',
        name: 'Rukita U-Town Bintaro',
        address: 'Ruko U Town Home no B08-B10 Kawasan Universitas Pembangunan Jaya, Pondok Aren, Sawah Lama, Ciputat,',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674040', name: 'CIPUTAT' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674040003', name: 'SAWAH BARU' },
        lat: -6.292209,
        lon: 106.726449,
        startFrom: 2500000,
        discount: {
          amount: 500000.0,
          name: 'Re-pricing (500,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'u-town',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-U-Town_Feb2020_81_Edit/b244e688ce998a77c0fecb31a968bd9a.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=ynODnDfOYq4',
        rukitaOption: false
      },
      {
        id: '185',
        name: "Rukita D'Teras Bintaro",
        address: 'Jl. RC. Veteran Raya No.8C, RT.3/RW.1, Bintaro, Kec. Pesanggrahan, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171040', name: 'PESANGGRAHAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171040001', name: 'BINTARO' },
        lat: -6.264021,
        lon: 106.766131,
        startFrom: 2300000,
        discount: null,
        published: false,
        slug: 'd-teras-bintaro',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-D_Teras-Bintaro_1_SvziENT/bbc5190a8c248b81f10c4263873278a8.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=iygc_GsP9ss',
        rukitaOption: false
      },
      {
        id: '250',
        name: 'Rukita Flamboyan Bintaro',
        address: 'Jl. WR Supratman, Jl. Buntu No. 8, Pondok Ranji, Bintaro, Tangerang Selatan',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674060', name: 'PONDOK AREN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674060010', name: 'PONDOK KARYA' },
        lat: -6.274523,
        lon: 106.743666,
        startFrom: 1500000,
        discount: null,
        published: false,
        slug: 'flamboyan-bintaro',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Flamboyan-Bintaro_September2020_11_edited/6b50bf9ddd03273089fcc80f56297b69.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '181',
        name: 'Rukita Safwah Bintaro Jaya',
        address: 'Jl. H. Som No.126, Pd. Pucung, Kec. Pd. Aren, Kota Tangerang Selatan, Banten',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674060', name: 'PONDOK AREN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674060005', name: 'PONDOK PUCUNG' },
        lat: -6.277188,
        lon: 106.714609,
        startFrom: 2700000,
        discount: null,
        published: true,
        slug: 'safwah-bintaro-jaya-pondok-aren',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Safwah-Bintaro-Jaya-Pondok-Aren_Juni2020_58_edited/6e0de341ed9bbba49866fe869bf4c2ed.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=aX7DM9gIzUY',
        rukitaOption: false
      },
      {
        id: '107',
        name: 'Rukita Deplu 11 Bintaro',
        address: 'Jl Deplu Raya No 11, RT4/RW3. Kel. Bintaro, Pesanggrahan. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171040', name: 'PESANGGRAHAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171040001', name: 'BINTARO' },
        lat: -6.25546,
        lon: 106.76311,
        startFrom: 2500000,
        discount: {
          amount: 600000.0,
          name: 'Re-pricing (600,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'deplu',
        roomAvailability: 15,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC07114/18d717783b5e6b21810bf3f43f3cf11b.JPG`,
        videoUrl: 'https://www.youtube.com/watch?v=Yxksy_ih-Mo',
        rukitaOption: false
      },
      {
        id: '179',
        name: 'Rukita Cendrawasih JM Bintaro',
        address: 'Jalan Cendrawasih no 6, Jurang Mangu Barat, Pondok Aren, Tangerang Selatan',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674060', name: 'PONDOK AREN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674060008', name: 'JURANG MANGGU BARAT' },
        lat: -6.267007,
        lon: 106.73607,
        startFrom: 2300000,
        discount: {
          amount: 800000.0,
          name: 'Re-pricing (800,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'jurang-mangu-cendrawasih-6',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Jurang-Mangu-Cenderawasih-6_April2020_56_edited/859e5d37454bdedfeeccea2b4e74b03d.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=E9APf-2u8HQ',
        rukitaOption: false
      }
    ]
  },
  {
    id: '85',
    name: 'Blok M',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '176',
        name: 'Rukita RKBM Gandaria',
        address: 'Ruko Kebayoran Baru Mall No 20-21. Jl Kebayoran Baru, Gunung',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.239063,
        lon: 106.785106,
        startFrom: 2900000,
        discount: null,
        published: true,
        slug: 'pakubuwono-rkbm',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pakubuwono-RKBM_Maret2020_1_edited/44585a726d05e947b13cd8c20d1acb1f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=31nZJxAfrSk&list=P',
        rukitaOption: false
      },
      {
        id: '251',
        name: 'Rukita Pinnus Cipete',
        address: 'Jalan Kirai No 6 , RT 08/RW 01, Cipete Utara, Kebayoran Baru, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060002', name: 'CIPETE UTARA' },
        lat: -6.258244,
        lon: 106.803499,
        startFrom: 3500000,
        discount: {
          amount: 500000.0,
          name: 'Re-pricing (500,000)',
          discountType: 'FLAT'
        },
        published: false,
        slug: 'pinnus-cipete',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pinnus-Cipete_September2020_1_edited/f9d0bf78384bcd27ad423d5ea9c2c883.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=_nXkmqLp3N4',
        rukitaOption: false
      },
      {
        id: '174',
        name: 'Rukita Tata Yumi Radio Dalam',
        address: 'Jalan Lobak III No 8, Kel Pulo, Kec Kebayoran Baru. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.254433,
        lon: 106.794148,
        startFrom: 3500000,
        discount: null,
        published: true,
        slug: 'blok-a-taya-yumi',
        roomAvailability: 9,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Blok-A-Tata-Yumi_Maret2020-1_edited/680e9076588a794491789f01d414165f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=cogACfplBCs',
        rukitaOption: false
      }
    ]
  },
  {
    id: '68',
    name: 'BSD',
    cityName: 'KABUPATEN TANGERANG',
    buildings: [
      {
        id: '160',
        name: 'Rukita Agape Studento BSD',
        address: 'Perumahan Foresta, Cluster Studento Blok L19 No 1. BSD. Pagedangan. Tangerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603070', name: 'PAGEDANGAN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603070006', name: 'PAGEDANGAN' },
        lat: -6.294789,
        lon: 106.640718,
        startFrom: 2400000,
        discount: {
          amount: 200000.0,
          name: 'Re-pricing (200,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'agape-studento-bsd',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Foresta-BSD-1_Feb2020_6_edited/693a14fe8ae1b7edfd5bdeb6617b1df8.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=0xY0fzmPMco',
        rukitaOption: false
      },
      {
        id: '171',
        name: 'Rukita Edelweis Studento BSD',
        address: 'Foresta Cluster Studento, Blk. L No.22 No.10, Banten',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674020', name: 'SERPONG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674020013', name: 'SERPONG' },
        lat: -6.295039,
        lon: 106.641073,
        startFrom: 2600000,
        discount: {
          amount: 300000.0,
          name: 'Re-pricing (300,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'edelweis-studento-bsd',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Foresta-BSD-22-_Maret2020_63_edited/135e07fa291be8a1c32912f168ebe0c8.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=zMaUpHY-c6Q',
        rukitaOption: false
      },
      {
        id: '132',
        name: 'Rukita Anggrek Loka BSD',
        address: 'Jl. Anggrek Lili II AC No.58, Rw. Buntu, Kec. Serpong, Kota Tangerang Selatan, Banten',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603070', name: 'PAGEDANGAN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603070006', name: 'PAGEDANGAN' },
        lat: -6.302383,
        lon: 106.67066,
        startFrom: 2000000,
        discount: null,
        published: true,
        slug: 'anggrek-loka-bsd',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Anggrek-Loka_Feb2020_edited-2/17d478a5997944e2f7f2b245a229f321.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Ycv2GZ2-Bvk',
        rukitaOption: false
      },
      {
        id: '159',
        name: 'Rukita Casablanca Studento BSD',
        address: 'Perumahan Foresta, Cluster Studento Blok L 16 No 9. BSD. Pagedangan. Tangerang',
        city: { id: '3674', name: 'KOTA TANGERANG SELATAN' },
        district: { id: '3674020', name: 'SERPONG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3674020013', name: 'SERPONG' },
        lat: -6.29504,
        lon: 106.641037,
        startFrom: 2200000,
        discount: null,
        published: true,
        slug: 'casablanca-studento-bsd',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Foresta-BSD-10_Feb2020_19/34e7e8b18ed15216956382e0d0e39af1.JPG`,
        videoUrl: 'https://www.youtube.com/watch?v=r0P76QvTAQ8',
        rukitaOption: false
      },
      {
        id: '167',
        name: 'Rukita Uni Studento BSD',
        address: 'Studento Blok L 22/9. Foresta, BSD City. Pagedangan. Banten, Tangerang, Banten 15331',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603070', name: 'PAGEDANGAN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603070006', name: 'PAGEDANGAN' },
        lat: -6.294956,
        lon: 106.641223,
        startFrom: 2400000,
        discount: null,
        published: true,
        slug: 'uni-studento-bsd',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Foresta-BSD-9_Feb2020_14/2bb3bac4b853ed91775bf1dea37208ef.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '263',
        name: 'Rukita Emerald Anarta House BSD',
        address: 'Jl. Cicayur I No.6, Cijantra, Kec. Pagedangan, Tangerang, Banten 15336',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603070', name: 'PAGEDANGAN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603070006', name: 'PAGEDANGAN' },
        lat: -6.29111602474193,
        lon: 106.619764511044,
        startFrom: 1600000,
        discount: null,
        published: false,
        slug: 'emerald-anarta-house-bsd',
        roomAvailability: 22,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Emerald-Anarta-House_Januari2021_9_1_/017cdee2eb5d370a75e6bd8f585e0a17.JPG`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '255',
        name: 'Rukita Bless Studento',
        address: 'Perumahan Foresta Cluster Studento Blok L15 No. 1, BSD City, Kabupaten Tangeran, Provinsi Banten',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603070', name: 'PAGEDANGAN' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603070006', name: 'PAGEDANGAN' },
        lat: -6.29559443468136,
        lon: 106.640901134111,
        startFrom: 1700000,
        discount: null,
        published: false,
        slug: 'bless-studento',
        roomAvailability: 9,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Bless-Studento_November2020_85_edited/bd114fb256e79986ece9d574cf0ff031.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=5MjwBa0c-LE',
        rukitaOption: false
      }
    ]
  },
  {
    id: '74',
    name: 'Cakung',
    cityName: 'KOTA JAKARTA TIMUR',
    buildings: [
      {
        id: '162',
        name: 'Rukita Melkan Cakung',
        address: 'Perumahan Taman Pulo Gebang Blok D6 No 12A. Cakung. Jakarta Timur',
        city: { id: '3172', name: 'KOTA JAKARTA TIMUR' },
        district: { id: '3172080', name: 'CAKUNG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3172080003', name: 'PULO GEBANG' },
        lat: -6.192747,
        lon: 106.94711,
        startFrom: 1700000,
        discount: null,
        published: true,
        slug: 'cakung',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Cakung_Maret2020_16/bb93a6584044a5eb7452a1b6ca8ddfbb.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '71',
    name: 'Cempaka Putih',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '156',
        name: 'Rukita MSR Cempaka Putih',
        address: 'Jl. Cempaka Putih Timur VII No.20 RT.4/RW.7, Cemp. Putih Tim. Kec. Cemp. Putih Kota Jakarta Pusat Da',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173050', name: 'CEMPAKA PUTIH' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173050002', name: 'CEMPAKA PUTIH TIMUR' },
        lat: -6.17394,
        lon: 106.873906,
        startFrom: 2800000,
        discount: null,
        published: true,
        slug: 'cempaka-putih',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Cempaka-Putih-Room-18_Maret-2020_81_edited/64a9648e6882de7252eb7cfe9d228b3c.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '23',
    name: 'Cengkareng',
    cityName: 'KOTA TANGERANG',
    buildings: [
      {
        id: '187',
        name: 'Rukita Cendrawasih 73 Cengkareng',
        address: 'Jalan Cendrawasih Raya no 73, Cengkareng, Jakarta Barat',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174070', name: 'CENGKARENG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174070006', name: 'CENGKARENG BARAT' },
        lat: -6.143855,
        lon: 106.72322,
        startFrom: 1600000,
        discount: null,
        published: false,
        slug: 'cendrawasih-73-cengkareng',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Cendrawasih-73-Cengkareng_Juli2020_69_edited/5d25c72bebc05c089d878ab73f604b6d.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '69',
    name: 'Cideng',
    cityName: 'KOTA JAKARTA BARAT',
    buildings: [
      {
        id: '253',
        name: 'Rukita Omah Roxy Cideng',
        address: 'Jalan Tanjung Selor No 5 RT 16/RW 06, Kel Cideng, Kec. Gambir, Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173080', name: 'GAMBIR' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173080001', name: 'CIDENG' },
        lat: -6.171751,
        lon: 106.805213,
        startFrom: 1800000,
        discount: null,
        published: false,
        slug: 'omah-roxy-cideng',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Omah-Roxy-Cideng_Oktober2020_63_edited_niI8mCA/e5b62e4501d90196a389ab3369c5e5d4.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '137',
        name: 'Rukita VIP Cideng',
        address: 'Jalan Palang Merah No 12, Kel Petojo, Kec Gambir Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173080', name: 'GAMBIR' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173080001', name: 'CIDENG' },
        lat: -6.169336,
        lon: 106.807015,
        startFrom: 2500000,
        discount: null,
        published: true,
        slug: 'cideng',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Gambir_Feb2020_edited-3/f9722cdcee1f2a1a8d646946aba29530.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '77',
    name: 'Cilandak',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '254',
        name: 'Rukita Moes Cipete',
        address: 'Jl.Cipete No. 2 RT.2/RW.6, Cipete Selatan, Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jak',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171030', name: 'CILANDAK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171030005', name: 'CIPETE SELATAN' },
        lat: -6.275345,
        lon: 106.798178,
        startFrom: 2600000,
        discount: null,
        published: false,
        slug: 'moes-cipete',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Moes-Cipete_Oktober2020_40_edited/679dae4e2c3b002babb4d2110198a3ac.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Q6ZLjD1kS3s',
        rukitaOption: false
      },
      {
        id: '49',
        name: 'Rukita Bonavista 17 Lebak Bulus',
        address: 'Jl. Bonavista Utama Blok B4 No.17',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171030', name: 'CILANDAK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171030001', name: 'LEBAK BULUS' },
        lat: -6.301953,
        lon: 106.784654,
        startFrom: 2700000,
        discount: null,
        published: true,
        slug: 'bonavista',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC07890_EDT_Quzn3ie/2c6b206d0a78586cb98bef2384a62e60.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=XPGqoO3IOcM',
        rukitaOption: false
      },
      {
        id: '169',
        name: 'Apartment Beverly Tower 1',
        address: 'Jl. R.A.Kartini No.16, Cilandak Bar., Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jak',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171030', name: 'CILANDAK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171030003', name: 'CILANDAK BARAT' },
        lat: -6.291101,
        lon: 106.786652,
        startFrom: 5000000,
        discount: null,
        published: true,
        slug: 'beverly-tower-1',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Beverly-Tower-Apartment-A06.1_Feb2020_6_Edit/6a567485303f0875c7cc6c3a447d28cd.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '165',
        name: 'Apartment Beverly Tower 2',
        address: 'Jl. R.A.Kartini No.16, Cilandak Bar., Kec. Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jak',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171030', name: 'CILANDAK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171030003', name: 'CILANDAK BARAT' },
        lat: -6.291104,
        lon: 106.786649,
        startFrom: 5000000,
        discount: null,
        published: true,
        slug: 'beverly-tower-2',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Beverly-Apartment-201_Feb2020_edited-1/986a12dd9604abef3477bb2845e8fd8d.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '67',
    name: 'Depok',
    cityName: 'KOTA DEPOK',
    buildings: [
      {
        id: '173',
        name: 'Rukita Sakura Depok',
        address: 'Jl Masjid Al Faruq No 31,RT 007/001 Kukusan, Kec Beji, Depok, Jawa Barat',
        city: { id: '3276', name: 'KOTA DEPOK' },
        district: { id: '3276050', name: 'BEJI' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3276050005', name: 'KUKUSAN' },
        lat: -6.359442,
        lon: 106.822498,
        startFrom: 1800000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'sakura-depok',
        roomAvailability: 78,
        photoThumbnail: `${_url}CACHE/images/buildings/building/4/a4e3ee96149409b289a4e90b5d28cc7e.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=6uFO8CnW5iY',
        rukitaOption: false
      },
      {
        id: '153',
        name: 'Rukita Akasia Depok',
        address: 'Jl. H. Amat II No.7, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat',
        city: { id: '3276', name: 'KOTA DEPOK' },
        district: { id: '3276050', name: 'BEJI' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3276050005', name: 'KUKUSAN' },
        lat: -6.361881,
        lon: 106.819759,
        startFrom: 1700000,
        discount: null,
        published: true,
        slug: 'akasia-depok',
        roomAvailability: 93,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Akasia-Feb2020-edited_7/44e29e2a6a75186f31b58991836629e8.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Pqab-_YxOx4',
        rukitaOption: false
      },
      {
        id: '155',
        name: 'Rukita Jasmine Depok',
        address: 'Jl. Juragan Sinda II No.54, RT 002/001, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat',
        city: { id: '3276', name: 'KOTA DEPOK' },
        district: { id: '3276050', name: 'BEJI' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3276050005', name: 'KUKUSAN' },
        lat: -6.357469,
        lon: 106.820411,
        startFrom: 1150000,
        discount: {
          amount: 300000.0,
          name: 'Re-pricing (300,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'jasmine-depok',
        roomAvailability: 64,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Jasmine-Fev2020-edited-2/abcef7ed32ab3cc5f90c03441b1dac01.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '152',
        name: 'Rukita Tulip Depok',
        address: 'Jl. H. Amat No.3A, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat 16425',
        city: { id: '3276', name: 'KOTA DEPOK' },
        district: { id: '3276050', name: 'BEJI' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3276050005', name: 'KUKUSAN' },
        lat: -6.359578,
        lon: 106.818929,
        startFrom: 1200000,
        discount: null,
        published: true,
        slug: 'tulip-depok',
        roomAvailability: 41,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Tulip_Feb2020_edit-2_H10stza/f2fe354716999f3fafa2d8a21799228d.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '154',
        name: 'Rukita Lavender Depok',
        address: 'Jl. H. Amat II No.52, Kukusan, Kecamatan Beji, Kota Depok, Jawa Barat',
        city: { id: '3276', name: 'KOTA DEPOK' },
        district: { id: '3276050', name: 'BEJI' },
        province: { id: '32', name: 'JAWA BARAT' },
        subdistrict: { id: '3276050005', name: 'KUKUSAN' },
        lat: -6.360716,
        lon: 106.820185,
        startFrom: 1700000,
        discount: null,
        published: true,
        slug: 'lavender-depok',
        roomAvailability: 97,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Lavender-Feb2020-edited-8/948727dfc647b2a0a3a140e27b14c5e2.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '86',
    name: 'Gandaria',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '176',
        name: 'Rukita RKBM Gandaria',
        address: 'Ruko Kebayoran Baru Mall No 20-21. Jl Kebayoran Baru, Gunung',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.239063,
        lon: 106.785106,
        startFrom: 2900000,
        discount: null,
        published: true,
        slug: 'pakubuwono-rkbm',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pakubuwono-RKBM_Maret2020_1_edited/44585a726d05e947b13cd8c20d1acb1f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=31nZJxAfrSk&list=P',
        rukitaOption: false
      }
    ]
  },
  {
    id: '9',
    name: 'Grogol',
    cityName: 'KOTA JAKARTA BARAT',
    buildings: [
      {
        id: '101',
        name: 'Rukita Permata Tomang',
        address: 'Jalan Permata No 6 RT.10/RW.9, Tomang Kec. Grogol petamburan Kota Jakarta Barat',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174040', name: 'GROGOL PETAMBURAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174040003', name: 'TOMANG' },
        lat: -6.1701,
        lon: 106.7958,
        startFrom: 2300000,
        discount: {
          amount: 200000.0,
          name: 'Re-pricing (200,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'permata-house',
        roomAvailability: 32,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC02114/ac5ea1ea7058b0641c0c5bea4a691a7b.JPG`,
        videoUrl: 'https://www.youtube.com/watch?v=mB6qnk20bEI',
        rukitaOption: false
      },
      {
        id: '261',
        name: 'Rukita Topaz Tawakal Tomang',
        address: 'Jl. Tawakal Raya No.32, RT.5/RW.9, Tomang, Jakarta, Kota Jakarta Barat, Daerah Khusus Ibukota Jakart',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174040', name: 'GROGOL PETAMBURAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174040003', name: 'TOMANG' },
        lat: -6.16872817946548,
        lon: 106.794901726627,
        startFrom: 1600000,
        discount: null,
        published: false,
        slug: 'topaz-tawakal-tomang',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Topaz-Tawakal-Tomang_Desember2020_123_edited/5e8e654bef18a1cb64642be1147a70cc.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '135',
        name: 'Rukita Residence Tawakal Tomang',
        address: 'Jl. Tawakal V No.6 RT.9/RW.9, Tomang Kec. Grogol petamburan Kota Jakarta Barat',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174040', name: 'GROGOL PETAMBURAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174040003', name: 'TOMANG' },
        lat: -6.1689607,
        lon: 106.7932061,
        startFrom: 3200000,
        discount: {
          amount: 500000.0,
          name: 'Re-pricing (500,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'tawakal-tomang',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Tawakal-Tomang_Mar2020_6_yGeH5y7/603fa41f59840bc30ab0af12f653c420.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=yFhUawC1_B4',
        rukitaOption: false
      }
    ]
  },
  {
    id: '84',
    name: 'Jatinegara',
    cityName: 'KOTA JAKARTA TIMUR',
    buildings: [
      {
        id: '257',
        name: 'Pangkalan House Jatiwaringin',
        address: 'Jl. Pangkalan Jati II No.14 RT.7/RW.13, Cipinang Melayu Kec. Makasar',
        city: { id: '3172', name: 'KOTA JAKARTA TIMUR' },
        district: { id: '3172040', name: 'MAKASAR' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3172040005', name: 'CIPINANG MELAYU' },
        lat: -6.24917536606037,
        lon: 106.90810054813,
        startFrom: 1950000,
        discount: null,
        published: false,
        slug: 'pangkalan-house-jatiwaringin',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/1_7FZoik9/d2564c617e0ce7fb15500c4c103a77a7.jpg`,
        videoUrl: null,
        rukitaOption: true
      },
      {
        id: '186',
        name: 'Rukita Kebon Nanas Cipinang',
        address: 'Jl. Griya Wartawan 24-26, RT.8/RW.5, Cipinang Besar Sel., Kecamatan Jatinegara, Kota Jakarta Timur,',
        city: { id: '3172', name: 'KOTA JAKARTA TIMUR' },
        district: { id: '3172060', name: 'JATINEGARA' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3172060003', name: 'CIPINANG BESAR SELATAN' },
        lat: -6.233382,
        lon: 106.883256,
        startFrom: 1200000,
        discount: null,
        published: false,
        slug: 'kebon-nanas-jatinegara',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/1_bfk24cy/0eaeaf69da4745b3f72f4a498732998d.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=pKwWjsGXiw4',
        rukitaOption: false
      }
    ]
  },
  {
    id: '4',
    name: 'Karawaci',
    cityName: 'KABUPATEN TANGERANG',
    buildings: [
      {
        id: '99',
        name: 'Rukita Kimbelloft Karawaci',
        address: 'Jl. Permata Sari Blok A3 No.39, RT.3/RW.1, Binong, Curug, Tangerang, Banten 15810, Indonesia',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603050', name: 'CURUG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603050007', name: 'BINONG' },
        lat: -6.226174,
        lon: 106.586387,
        startFrom: 4300000,
        discount: null,
        published: true,
        slug: 'kimbelloft-karawaci',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Karawaci_Feb2020_28/80e72cccceb5fecaf140cc386711dd7c.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=2mtMyyeNItg',
        rukitaOption: false
      },
      {
        id: '117',
        name: 'Rukita Bromo 10 Karawaci',
        address: 'Jl. Gunung Bromo No.10, bencongan, curug, Tanggerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603050', name: 'CURUG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603051006', name: 'BENCONGAN' },
        lat: -6.234405,
        lon: 106.59408,
        startFrom: 2000000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'bromo-10',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Bromo-10_Maret2020_10_edited_urlyVKg/40ec2362c486a4541da9642ab255d253.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=a3k6FTbHMU8',
        rukitaOption: false
      },
      {
        id: '115',
        name: 'Rukita Bromo 18 Karawaci',
        address: 'Jl. Gunung Bromo No.18, bencongan, curug, Tanggerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603051', name: 'KELAPA DUA' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603051006', name: 'BENCONGAN' },
        lat: -6.234235,
        lon: 106.59379,
        startFrom: 2000000,
        discount: {
          amount: 600000.0,
          name: 'Re-pricing (600,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'bromo-18',
        roomAvailability: 10,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Bromo-18_Maret2020_30/940a799afeee541c3f3873b2c08b1349.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=dO1ybv6b1Mo&t=1s',
        rukitaOption: false
      },
      {
        id: '129',
        name: 'Rukita Bromo 56 Karawaci',
        address: 'Jl Gunung Timur No 56. Kel Bencongan Indah. Kec Kelapa Dua. Tangerang. Banten',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603051', name: 'KELAPA DUA' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603051006', name: 'BENCONGAN' },
        lat: -6.233405,
        lon: 106.594483,
        startFrom: 2100000,
        discount: null,
        published: true,
        slug: 'bromo-56',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Bromo-56_Jan2020_76_Edit/8e9e20ed4fa4ca143899c4c0628b6a24.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '183',
        name: 'Rukita Kutu Buku Karawaci',
        address: 'Jl Permata Sari 3 Blok A4 No 25. Karawaci, Binong, Curug , Tangerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603050', name: 'CURUG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603050007', name: 'BINONG' },
        lat: -6.226708,
        lon: 106.587761,
        startFrom: 4000000,
        discount: null,
        published: true,
        slug: 'kutu-buku-karawaci',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Kutu-Buku-Karawaci_Mei2020_157_edited/02d0efd0c6ca66ec8fd8a64379e62381.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=hjUUJz5_k9k',
        rukitaOption: false
      },
      {
        id: '161',
        name: 'Rukita El-Gracia Karawaci',
        address: 'Jl Permata Indah VI blok B6 No 56. Kel Binong. Kec Curug Tangerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603050', name: 'CURUG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603050007', name: 'BINONG' },
        lat: -6.227894,
        lon: 106.589309,
        startFrom: 4000000,
        discount: null,
        published: true,
        slug: 'el-gracia-karawaci',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Taman-Permata_Feb2020_65_Edit/5b07c56e60f0e93d7fe756123628bcdb.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=EW5kpUTmz-Q',
        rukitaOption: false
      },
      {
        id: '116',
        name: 'Rukita Bromo 6 Karawaci',
        address: 'Jl. Gunung Bromo No.6, bencongan, curug, Tanggerang',
        city: { id: '3603', name: 'KABUPATEN TANGERANG' },
        district: { id: '3603050', name: 'CURUG' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3603050007', name: 'BINONG' },
        lat: -6.234322,
        lon: 106.594166,
        startFrom: 2000000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'bromo-6',
        roomAvailability: 10,
        photoThumbnail: `${_url}CACHE/images/buildings/building/2_gcBfGuD/016c207f55b46b658f5abdfa207329ee.JPG`,
        videoUrl: 'https://www.youtube.com/watch?v=tn_XBspEPqM',
        rukitaOption: false
      }
    ]
  },
  {
    id: '78',
    name: 'Kebayoran Baru',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '176',
        name: 'Rukita RKBM Gandaria',
        address: 'Ruko Kebayoran Baru Mall No 20-21. Jl Kebayoran Baru, Gunung',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.239063,
        lon: 106.785106,
        startFrom: 2900000,
        discount: null,
        published: true,
        slug: 'pakubuwono-rkbm',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pakubuwono-RKBM_Maret2020_1_edited/44585a726d05e947b13cd8c20d1acb1f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=31nZJxAfrSk&list=P',
        rukitaOption: false
      },
      {
        id: '251',
        name: 'Rukita Pinnus Cipete',
        address: 'Jalan Kirai No 6 , RT 08/RW 01, Cipete Utara, Kebayoran Baru, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060002', name: 'CIPETE UTARA' },
        lat: -6.258244,
        lon: 106.803499,
        startFrom: 3500000,
        discount: {
          amount: 500000.0,
          name: 'Re-pricing (500,000)',
          discountType: 'FLAT'
        },
        published: false,
        slug: 'pinnus-cipete',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pinnus-Cipete_September2020_1_edited/f9d0bf78384bcd27ad423d5ea9c2c883.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=_nXkmqLp3N4',
        rukitaOption: false
      },
      {
        id: '254',
        name: 'Rukita Moes Cipete',
        address: 'Jl.Cipete No. 2 RT.2/RW.6, Cipete Selatan, Cilandak, Kota Jakarta Selatan, Daerah Khusus Ibukota Jak',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171030', name: 'CILANDAK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171030005', name: 'CIPETE SELATAN' },
        lat: -6.275345,
        lon: 106.798178,
        startFrom: 2600000,
        discount: null,
        published: false,
        slug: 'moes-cipete',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Moes-Cipete_Oktober2020_40_edited/679dae4e2c3b002babb4d2110198a3ac.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Q6ZLjD1kS3s',
        rukitaOption: false
      },
      {
        id: '174',
        name: 'Rukita Tata Yumi Radio Dalam',
        address: 'Jalan Lobak III No 8, Kel Pulo, Kec Kebayoran Baru. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.254433,
        lon: 106.794148,
        startFrom: 3500000,
        discount: null,
        published: true,
        slug: 'blok-a-taya-yumi',
        roomAvailability: 9,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Blok-A-Tata-Yumi_Maret2020-1_edited/680e9076588a794491789f01d414165f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=cogACfplBCs',
        rukitaOption: false
      }
    ]
  },
  {
    id: '25',
    name: 'Kebon Jeruk',
    cityName: 'KOTA JAKARTA BARAT',
    buildings: [
      {
        id: '124',
        name: 'Rukita E Homes Kebon Jeruk',
        address: 'Jalan E no 19. Kel Kebon Jeruk. Kec Kebon Jeruk. Jakarta Barat',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174020', name: 'KEBON JERUK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174020004', name: 'KEBON JERUK' },
        lat: -6.202187,
        lon: 106.76765,
        startFrom: 2700000,
        discount: null,
        published: true,
        slug: 'kebon-jeruk',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/_HAN5639/afaf01dd57351daeb5c934f3cc2625e8.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '75',
    name: 'Kemang',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '125',
        name: 'Rukita Bangka Kemang',
        address: 'Jalan Bangka XI No 64. Kel Bangka, Kemang, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171070', name: 'MAMPANG PRAPATAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171070001', name: 'BANGKA' },
        lat: -6.254183,
        lon: 106.818811,
        startFrom: 3700000,
        discount: null,
        published: true,
        slug: 'kemang',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Kemang_Maret2020_9_edited/f075170ccac5b48159d8001dcb4d425d.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '10',
    name: 'Kuningan',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '182',
        name: 'Rukita Verde Residence Kuningan',
        address: 'Jl. Pedurenan Masjid 5 No.28, RT.1/RW.4, Kuningan, Karet Kuningan, Kecamatan Setiabudi, Kota Jakarta',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100003', name: 'KARET KUNINGAN' },
        lat: -6.222238,
        lon: 106.829292,
        startFrom: 3300000,
        discount: {
          amount: 700000.0,
          name: 'Re-pricing (700,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'verde-residence-kuningan',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Verde-Residence-Kuningan_Mei2020_39_edited/780e57cfa7a28d4ddb6c3cc934634edc.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=89fmyHynaVA',
        rukitaOption: false
      },
      {
        id: '97',
        name: 'Taman Rasuna Apartment',
        address: 'Jalan Hr. Rasuna Said, RT.2/RW.5, Karet Kuningan, RT.16/RW.1, Menteng Atas, Kota Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100003', name: 'KARET KUNINGAN' },
        lat: -6.21943,
        lon: 106.8365,
        startFrom: 4500000,
        discount: null,
        published: true,
        slug: 'taman-rasuna',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC00100_Edit/26e7079aa4b42071ba7b70005d8af162.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '93',
        name: 'Ciputra World II',
        address: 'Jl. Prof. DR Sartrio No. 7 Karet Semanggi Setia Budi',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100001', name: 'KARET SEMANGGI' },
        lat: -6.222573,
        lon: 106.820004,
        startFrom: 9000000,
        discount: null,
        published: true,
        slug: 'ciputra-world',
        roomAvailability: 9,
        photoThumbnail: `${_url}CACHE/images/buildings/building/_HAN3401_4ThlCMn/1605359553be7ec7c303f6fb2c74ce95.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=daNqgN8QanI',
        rukitaOption: false
      },
      {
        id: '123',
        name: 'Bellagio Residence',
        address: 'Jl. Mega Kuningan Barat No.3, RT 5/RW 2, Kuningan Timur, Setiabudi, Kota Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100002', name: 'KUNINGAN TIMUR' },
        lat: -6.225968,
        lon: 106.824543,
        startFrom: 8750000,
        discount: null,
        published: true,
        slug: 'bellagio-residence',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Bellagio-Residence-23BF03_Juni2020_25_edited/91bb1ff814bf3eaa2d44417702b30278.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '112',
    name: 'Mampang',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '259',
        name: 'Rukita Bunda Mampang Prapatan',
        address: 'Jl. Tegal Parang Sel. No.10 RT.6/RW.2, Tegal Parang Kec. Mampang Prpt. Kota Jakarta Selatan Daerah K',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171070', name: 'MAMPANG PRAPATAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171070003', name: 'TEGAL PARANG' },
        lat: -6.24580266240876,
        lon: 106.831943947246,
        startFrom: 3000000,
        discount: null,
        published: false,
        slug: 'bunda-mampang',
        roomAvailability: 20,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Bunda-Mampang-Prapatan_Desember2020_39_edited_VzyKXQz/d79a1d8a96df300b28ee336ebc7d4b94.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '80',
    name: 'Mangga Besar',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '130',
        name: 'Rukita Dwiwarna Mangga Besar',
        address: 'Jl Dwiwarna Raya II No 48. RT 001/009. Kel Kartini Kec Sawah Besar, Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '9471044', name: 'Sawah Besar' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '9471040009', name: 'Kartini' },
        lat: -6.149147,
        lon: 106.829496,
        startFrom: 2600000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'dwiwarna-raya',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Kartini-Dwiwarna-48_Maret2020_213_edited/d1318d902346aa5c540ca6704ff358ef.jpg`,
        videoUrl: 'https://youtu.be/VTnwOvu6Mp0',
        rukitaOption: false
      }
    ]
  },
  {
    id: '18',
    name: 'Manggarai',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '108',
        name: 'Rukita Lendeha Hills Manggarai',
        address: 'Jl Manggis I No 3. RT11/ RW 04. Manggarai Selatan. Tebet. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171090', name: 'TEBET' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171090006', name: 'MANGGARAI SELATAN' },
        lat: -6.22554,
        lon: 106.84953,
        startFrom: 3100000,
        discount: {
          amount: 250000.0,
          name: 'Re-pricing (250,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'manggarai',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/_HAN3036_Kbo7Ofy/972bfba50e58b946aa1d53b7648578f7.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Is3pupnmf1w',
        rukitaOption: false
      }
    ]
  },
  {
    id: '6',
    name: 'Menteng',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '170',
        name: 'Rukita Kudus Menteng',
        address: 'Jl. Kudus No.4 RW.6, Dukuh Atas, Menteng Kec. Menteng Kota Jakarta Pusat Daerah Khusus Ibukota Jakar',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173020', name: 'MENTENG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '9471040042', name: 'Dukuh Atas' },
        lat: -6.201181,
        lon: 106.825025,
        startFrom: 3100000,
        discount: null,
        published: true,
        slug: 'menteng-kudus',
        roomAvailability: 6,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Menteng-Kudus-4_Maret2020_157_edited/d868383c11756ce4d0af6b514ab8fdf4.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '60',
        name: 'Menteng Square',
        address: 'Jalan Matraman No.30E 6 6, RT.5/RW.6, Kenari, Kec. Senen, Kota Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173030', name: 'SENEN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173030001', name: 'KENARI' },
        lat: -6.201379,
        lon: 106.851339,
        startFrom: 3000000,
        discount: null,
        published: true,
        slug: 'menteng-square',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC01340/1cb3e84cadf01ad4df921929b26e1d62.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=K7lkrPOYzdc',
        rukitaOption: false
      }
    ]
  },
  {
    id: '79',
    name: 'Pancoran',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '256',
        name: 'Rukita Triloka Mansion Pancoran',
        address: 'Komplek Triloka TNI AU Jl. Triloka 1, Kavling V, No.45, RT.1/RW.6, Pancoran, Kec. Pancoran, Kota Ja',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171080', name: 'PANCORAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171080004', name: 'PANCORAN' },
        lat: -6.24861222482273,
        lon: 106.842076973013,
        startFrom: 2500000,
        discount: null,
        published: false,
        slug: 'triloka-mansion-pancoran',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Triloka-Mansion_November2020_23_edited/1acb1ee4a6b4950fe58c1fcc0b2e6832.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '177',
        name: 'Rukita Potlot Duren Tiga',
        address: 'Jalan Potlot No II 30. RT 002/003. Kel Duren Tiga. Kec Pancoran. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171080', name: 'PANCORAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171080003', name: 'DUREN TIGA' },
        lat: -6.254978,
        lon: 106.839995,
        startFrom: 2900000,
        discount: null,
        published: true,
        slug: 'duren-tiga-potlot-30',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Duren-Tiga-Potlot-30_Maret2020_19_edited/92f152b31e82af203f49bb319e73e077.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '217',
        name: 'Rukita Rosewood Duren Tiga',
        address: 'Jl. Pancoran Barat VII No.27, RT.12, Pancoran, Kec. Pancoran, Kota Jakarta Selatan, Daerah Khusus Ib',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171080', name: 'PANCORAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171080003', name: 'DUREN TIGA' },
        lat: -6.252099,
        lon: 106.837547,
        startFrom: 2900000,
        discount: null,
        published: false,
        slug: 'rosewood-duren-tiga',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Rosewood-Duren-Tiga_September2020_1_edited/5259c80d4f96f06aafc10d8326f045d3.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '19',
    name: 'Pasar Baru',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '118',
        name: 'Rukita Kelinci Bunder Pasar Baru',
        address: 'Jl Kelinci Bunder No 9, Pasar Baru, Sawah Besar, Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173060', name: 'KEMAYORAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173060008', name: 'GUNUNG SAHARI SELATAN' },
        lat: -6.161979,
        lon: 106.83643,
        startFrom: 2400000,
        discount: null,
        published: true,
        slug: 'pasar-baru',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pasar-Baru_Feb2020_52_edited/3f6596f137368c6b6f8e3e28411c54dc.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=M5ayuyieOco',
        rukitaOption: false
      }
    ]
  },
  {
    id: '83',
    name: 'Pasar Minggu',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '260',
        name: 'Rukita KLS Pasar Minggu',
        address: 'Jl. Teluk Bone 103B, RT.6/RW.8, Ps. Minggu, Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus I',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171020', name: 'PASAR MINGGU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171020004', name: 'PASAR MINGGU' },
        lat: -6.30031788150355,
        lon: 106.839891165402,
        startFrom: 3100000,
        discount: null,
        published: false,
        slug: 'kls-pasar-minggu',
        roomAvailability: 12,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-KLS-Pasar-Minggu_Desember2020_27_edited/a70dbbe527494911877d70e777cd8a5b.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '94',
        name: 'Rukita Kebagusan City',
        address: 'Jl. Baung Raya Tanjung Barat, RT.2/RW.3, Kebagusan, Kec. Ps. Minggu, Kota Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171020', name: 'PASAR MINGGU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171020003', name: 'KEBAGUSAN' },
        lat: -6.306209,
        lon: 106.837155,
        startFrom: 4000000,
        discount: null,
        published: true,
        slug: 'kebagusan-city',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/kb10_hBUtOp0/d0bf56071d360b47230110244c5a6318.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '24',
    name: 'Pejaten',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '164',
        name: 'Rukita Jati Anom Pejaten',
        address: 'Jl. Jatianom No.9 RT.3/RW.7, Jati Padang Kec. Ps. Minggu Kota Jakarta Selatan Daerah Khusus Ibukota',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171020', name: 'PASAR MINGGU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171020005', name: 'JATI PADANG' },
        lat: -6.284241,
        lon: 106.829532,
        startFrom: 2700000,
        discount: null,
        published: false,
        slug: 'jati-anom',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Jati-Anom_Maret2020_7_edited/becd1959953ac51aa86de7d610b92101.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '96',
        name: 'Royal Olives Residence',
        address: 'Jl. Pejaten Raya Blok H Usman No.5, RT.1/RW.7, Pejaten Barat Kec. Ps. Minggu, Kota Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171020', name: 'PASAR MINGGU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171020006', name: 'PEJATEN BARAT' },
        lat: -6.276808,
        lon: 106.829194,
        startFrom: 5000000,
        discount: null,
        published: true,
        slug: 'royal-olive-residence',
        roomAvailability: 4,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC09680-Edit/02e88ac3f5256accc5b50f8a535718ad.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '87',
    name: 'Pesanggrahan',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '189',
        name: 'Rukita Ayama Pesanggrahan',
        address: 'Jalan Perdatam 3 No 10, RT 8/ RW 05. Kel Ulujami, Kec Pesanggrahan. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171040', name: 'PESANGGRAHAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171040003', name: 'ULUJAMI' },
        lat: -6.239618,
        lon: 106.764613,
        startFrom: 2500000,
        discount: null,
        published: false,
        slug: 'ayama-pesanggrahan',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Ayama-Pesanggrahan_Agustus2020_19_edited/c35f6a5876b6a9127007f10c5440b17d.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=vb94Ik0GvDc',
        rukitaOption: false
      }
    ]
  },
  {
    id: '76',
    name: 'Pluit',
    cityName: 'KOTA JAKARTA UTARA',
    buildings: [
      {
        id: '172',
        name: 'Rukita Permai Pluit',
        address: 'Jl Pluit Permai I No 31A. Kel Pluit. Kec Penjaringan. Jakarta Utara',
        city: { id: '3175', name: 'KOTA JAKARTA UTARA' },
        district: { id: '3175010', name: 'PENJARINGAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3175010005', name: 'PLUIT' },
        lat: -6.115286,
        lon: 106.789924,
        startFrom: 3200000,
        discount: null,
        published: true,
        slug: 'pluit-permai',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pluit-Permai_Maret2020_19_edited/9c846cb8ad545e86d351011239fc9b8a.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '20',
    name: 'Radio Dalam',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '262',
        name: 'Rukita Hidup Baru Fatmawati',
        address: 'Jl. Hidup Baru 6-57 RT.1/RW.7, Gandaria Utara Kec. Kby. Baru',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060001', name: 'GANDARIA UTARA' },
        lat: -6.26130293166172,
        lon: 106.795303297316,
        startFrom: 2600000,
        discount: null,
        published: false,
        slug: 'hidup-baru-fatmawati',
        roomAvailability: 19,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Hidup-Baru-Radio-Dalam_Januari2020_11_edited/cede1ec88acb3092b5b5b647d0ae40fe.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '251',
        name: 'Rukita Pinnus Cipete',
        address: 'Jalan Kirai No 6 , RT 08/RW 01, Cipete Utara, Kebayoran Baru, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060002', name: 'CIPETE UTARA' },
        lat: -6.258244,
        lon: 106.803499,
        startFrom: 3500000,
        discount: {
          amount: 500000.0,
          name: 'Re-pricing (500,000)',
          discountType: 'FLAT'
        },
        published: false,
        slug: 'pinnus-cipete',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Pinnus-Cipete_September2020_1_edited/f9d0bf78384bcd27ad423d5ea9c2c883.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=_nXkmqLp3N4',
        rukitaOption: false
      },
      {
        id: '128',
        name: 'Rukita Antene Radio Dalam',
        address: 'Jl. Antene I No.10, RT.8/RW.12, Gandaria Utara, Kec. Kby. Baru, Kota Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060001', name: 'GANDARIA UTARA' },
        lat: -6.250096,
        lon: 106.79268,
        startFrom: 4800000,
        discount: null,
        published: true,
        slug: 'radio-dalam-10',
        roomAvailability: 8,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Radio-Dalam-10_Feb2020_edited-10/896a0755df9b4d128916a13f274b5067.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Eo0zr4s09HQ',
        rukitaOption: false
      },
      {
        id: '174',
        name: 'Rukita Tata Yumi Radio Dalam',
        address: 'Jalan Lobak III No 8, Kel Pulo, Kec Kebayoran Baru. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060003', name: 'PULO' },
        lat: -6.254433,
        lon: 106.794148,
        startFrom: 3500000,
        discount: null,
        published: true,
        slug: 'blok-a-taya-yumi',
        roomAvailability: 9,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Blok-A-Tata-Yumi_Maret2020-1_edited/680e9076588a794491789f01d414165f.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=cogACfplBCs',
        rukitaOption: false
      }
    ]
  },
  {
    id: '70',
    name: 'Rawamangun',
    cityName: 'KOTA JAKARTA TIMUR',
    buildings: [
      {
        id: '127',
        name: 'Rukita Balai Pustaka Rawamangun',
        address: 'Jl. Balai Pustaka No.19, RT.7/RW.15, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur',
        city: { id: '3172', name: 'KOTA JAKARTA TIMUR' },
        district: { id: '3172090', name: 'PULO GADUNG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3172090005', name: 'RAWAMANGUN' },
        lat: -6.196162,
        lon: 106.884349,
        startFrom: 2700000,
        discount: null,
        published: true,
        slug: 'balai-pustaka',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Balai-Pustaka_Feb2020_10_edited/a978f485aad77ba9b44ef5f256432675.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '7',
    name: 'Senayan',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '119',
        name: 'Rukita Grasta Senayan',
        address: 'Jl. Asia Afrika Komplek PLN No. 11 Senayan, Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060010', name: 'SENAYAN' },
        lat: -6.216226,
        lon: 106.794194,
        startFrom: 3000000,
        discount: null,
        published: true,
        slug: 'senayan',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/2_Qyn810h/e254c7a3a65f9a957fc633e12cd28595.jpg`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '63',
        name: 'Rukita Biduri Permata Hijau',
        address: 'Jalan Taman Biduri I N2 no 7 RT.5/RW.1 Grogol Utara Kebayoran Lama, Jakarta',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171050', name: 'KEBAYORAN LAMA' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171050006', name: 'GROGOL UTARA' },
        lat: -6.216932,
        lon: 106.779783,
        startFrom: 4500000,
        discount: null,
        published: true,
        slug: 'permata-hijau-taman-biduri',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC07461/4fd07995243087bcffade0ef4a205240.JPG`,
        videoUrl: null,
        rukitaOption: false
      },
      {
        id: '62',
        name: 'Rukita Garnet Permata Hijau',
        address: 'Jl. Garnet Blok J2 No.12RT.8/RW.1, Grogol Utara, Kec. Kby. Lama, Kota Jakarta Selatan, Daerah Khusu',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171050', name: 'KEBAYORAN LAMA' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171050006', name: 'GROGOL UTARA' },
        lat: -6.216438,
        lon: 106.782601,
        startFrom: 4500000,
        discount: null,
        published: true,
        slug: 'permata-hijau-garnet',
        roomAvailability: 1,
        photoThumbnail: `${_url}CACHE/images/buildings/building/8/9733d8bcaf587b0a952a996c17f22480.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '13',
    name: 'Senopati',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '105',
        name: 'Rukita Dream Home Senopati',
        address: 'Jl Rengas 1 No 24, Blok S. Kebayoran Baru. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171060', name: 'KEBAYORAN BARU' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171060009', name: 'RAWA BARAT' },
        lat: -6.24319,
        lon: 106.79985,
        startFrom: 4000000,
        discount: {
          amount: 700000.0,
          name: 'Re-pricing (700,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'blok-s',
        roomAvailability: 7,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC06796/c4910e7caacd3b172a450a62424439d2.JPG`,
        videoUrl: 'https://www.youtube.com/watch?v=U1KZIGt8u9o&list=P',
        rukitaOption: false
      }
    ]
  },
  {
    id: '5',
    name: 'Setiabudi',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '102',
        name: 'Rukita Pacific Setiabudi',
        address: 'Jl. Taman Setia Budi II No.15RT.1/RW.6, Kuningan, Setia Budi, Kecamatan Setiabudi',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100003', name: 'KARET KUNINGAN' },
        lat: -6.207242,
        lon: 106.83051,
        startFrom: 4500000,
        discount: {
          amount: 650000.0,
          name: 'Re-pricing (650,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'pacific-setiabudi',
        roomAvailability: 7,
        photoThumbnail: `${_url}CACHE/images/buildings/building/1_F7gnWGs/dfe98ec116e16282731156946b836576.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=Ov3Ntp471LQ&t=1sht',
        rukitaOption: false
      },
      {
        id: '103',
        name: 'Rukita Capital Setiabudi',
        address: 'Jl Setiabudi VIII No 3. RT 2/RW 3. Kuningan. Setiabudi, Jakarta Selatan. DKI Jakarta 12910',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100003', name: 'KARET KUNINGAN' },
        lat: -6.207632,
        lon: 106.825311,
        startFrom: 4000000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'capital-setiabudi',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/2_oebM7wM/3a71bdedf6d08e7d0d874ebbeb5f77c6.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=TqHZ9mqwqjY',
        rukitaOption: false
      },
      {
        id: '104',
        name: 'Rukita Taman Setiabudi',
        address: 'Jalan Taman Setiabudi II No 9. Setiabudi. Kec Setiabudi. Jakarta Selatan',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171100', name: 'SETIA BUDI' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171100003', name: 'KARET KUNINGAN' },
        lat: -6.2082859,
        lon: 106.8239643,
        startFrom: 4400000,
        discount: null,
        published: true,
        slug: 'taman-setiabudi',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC08015-Edit/aafbf90fd3a682cf572ac8b3a16bc4e4.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '72',
    name: 'Tanah Abang',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '100',
        name: 'Rukita Cozy Rooms Benhil',
        address: 'Jl. Pam Lama no. 1K, Penjernihan 2, RT 008 / RW 006, Tanah Abang, Bendungan Hilir, Jakarta, Indonesi',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173010', name: 'TANAH ABANG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173010002', name: 'BENDUNGAN HILIR' },
        lat: -6.203306,
        lon: 106.807322,
        startFrom: 2000000,
        discount: null,
        published: true,
        slug: 'cozy-benhil',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/DSC00316-EDT_yufFYx3/7d0ed7aa5b3d3dc58077bac21743e894.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=ynUd2aLrTUc',
        rukitaOption: false
      }
    ]
  },
  {
    id: '21',
    name: 'Tangerang',
    cityName: 'KOTA TANGERANG',
    buildings: [
      {
        id: '178',
        name: 'Rukita Unicorn Otista Tangerang',
        address: 'Jl. Oto Iskandardinata No.24, RT.002/RW.006, Gerendeng, Kec. Karawaci, Kota Tangerang, Banten',
        city: { id: '3671', name: 'KOTA TANGERANG' },
        district: { id: '3671031', name: 'KARAWACI' },
        province: { id: '36', name: 'BANTEN' },
        subdistrict: { id: '3671031004', name: 'KARAWACI' },
        lat: -6.170309,
        lon: 106.625589,
        startFrom: 2300000,
        discount: {
          amount: 400000.0,
          name: 'Re-pricing (400,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'otista-unicorn-tangerang',
        roomAvailability: 5,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Tangerang-Otista-Unicorn_Maret2020_47_edited/61b992d1838a05c8cbee3584cbd349ab.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=9BDCAXUerRQ',
        rukitaOption: false
      }
    ]
  },
  {
    id: '82',
    name: 'Tanjung Duren',
    cityName: 'KOTA JAKARTA BARAT',
    buildings: [
      {
        id: '184',
        name: 'Rukita TDM Mansion Tanjung Duren',
        address: 'Jalan Taman Daan Mogot 1 no 4. Jakarta Barat',
        city: { id: '3174', name: 'KOTA JAKARTA BARAT' },
        district: { id: '3174040', name: 'GROGOL PETAMBURAN' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3174040001', name: 'TANJUNG DUREN UTARA' },
        lat: -6.1689704,
        lon: 106.7811705,
        startFrom: 2350000,
        discount: {
          amount: 600000.0,
          name: 'Re-pricing (600,000)',
          discountType: 'FLAT'
        },
        published: true,
        slug: 'tdm-mansion-tanjung-duren',
        roomAvailability: 44,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-TDM-Mansion-Tanjung-Duren_Juni2020_61_edited/2a66bbc453760c068ed70cba4db357a8.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=IM2auuCim2o',
        rukitaOption: false
      }
    ]
  },
  {
    id: '26',
    name: 'Tanjung Priok',
    cityName: 'KOTA JAKARTA UTARA',
    buildings: [
      {
        id: '126',
        name: 'Rukita Metro Indah Sunter',
        address: 'Jalan Metro Indah Raya A1 no 16 Jl. Metro Indah Raya No.16, RT.1/RW.4, Papanggo, Tanjung Priok',
        city: { id: '3175', name: 'KOTA JAKARTA UTARA' },
        district: { id: '3175030', name: 'TANJUNG PRIOK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3175030003', name: 'PAPANGO' },
        lat: -6.13543,
        lon: 106.87398,
        startFrom: 1800000,
        discount: null,
        published: true,
        slug: 'sunter',
        roomAvailability: 3,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Sunter_Feb2020_35_Edit/1bab12e9af80ac29928de9796b4417a9.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=w6TnIlCwvVM',
        rukitaOption: false
      },
      {
        id: '163',
        name: 'Rukita Pratama Sunter Agung',
        address: 'Jalan Selat Malaka Blok G No 1B. Kel Sunter Agung. Kec Tanjung Priok. Jakarta Utara',
        city: { id: '3175', name: 'KOTA JAKARTA UTARA' },
        district: { id: '3175030', name: 'TANJUNG PRIOK' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3175030001', name: 'SUNTER AGUNG' },
        lat: -6.131757,
        lon: 106.852948,
        startFrom: 2500000,
        discount: null,
        published: true,
        slug: 'pratama-sunter-agung',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Rukita-Sunter-Agung-Roteno_April2020_28_edited/1442369f437806481994331efcfff9a9.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '73',
    name: 'Tebet',
    cityName: 'KOTA JAKARTA SELATAN',
    buildings: [
      {
        id: '133',
        name: 'Rukita 98 Residence Tebet',
        address: 'Jl. Tebet Raya No.98, RT.1/RW.3, Tebet Tim., Kec. Tebet, Kota Jakarta Selatan, Daerah Khusus Ibukota',
        city: { id: '3171', name: 'KOTA JAKARTA SELATAN' },
        district: { id: '3171090', name: 'TEBET' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3171090003', name: 'TEBET TIMUR' },
        lat: -6.227243,
        lon: 106.857732,
        startFrom: 2400000,
        discount: null,
        published: true,
        slug: 'tebet',
        roomAvailability: 0,
        photoThumbnail: `${_url}CACHE/images/buildings/building/1_HnCUSM1/a5c43e71dc8d5c2211e2d79de1183a05.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  },
  {
    id: '12',
    name: 'Thamrin',
    cityName: 'KOTA JAKARTA PUSAT',
    buildings: [
      {
        id: '61',
        name: 'Thamrin Residence',
        address: 'Jalan Kebon Kacang Raya, RT.3/RW.8, Kb. Melati,  Tanahabang, Kota Jakarta Pusat',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173010', name: 'TANAH ABANG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173010004', name: 'KEBON MELATI' },
        lat: -6.194262,
        lon: 106.818633,
        startFrom: 4500000,
        discount: null,
        published: true,
        slug: 'thamrin-residence',
        roomAvailability: 11,
        photoThumbnail: `${_url}CACHE/images/buildings/building/38CB6/c77010baea0e336cce135dace6be4680.jpg`,
        videoUrl: 'https://www.youtube.com/watch?v=9H8Nrpk2ryA',
        rukitaOption: false
      },
      {
        id: '136',
        name: 'Sahid Sudirman Residence',
        address: 'Sahid Sudirman Residence Jend. Sudirman No. 86 DKI Jakarta 10220, RT.10/RW.11, Karet Tengsin',
        city: { id: '3173', name: 'KOTA JAKARTA PUSAT' },
        district: { id: '3173010', name: 'TANAH ABANG' },
        province: { id: '31', name: 'DKI JAKARTA' },
        subdistrict: { id: '3173010003', name: 'KARET TENGSIN' },
        lat: -6.20998,
        lon: 106.819545,
        startFrom: 5000000,
        discount: null,
        published: true,
        slug: 'sahid-sudirman-residence',
        roomAvailability: 2,
        photoThumbnail: `${_url}CACHE/images/buildings/building/Sahid-Sudirman-20E_Jan2020_13_Edit/c797730ae5527258436f88ae5b9b6ed5.jpg`,
        videoUrl: null,
        rukitaOption: false
      }
    ]
  }
];

export default places;
